# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ci0Yjs8n2tWorA0QX7_Xso8u-XwAb4Ef

# Proyek Analisis Data: Air Quality
- **Nama:** Azarine Nasya Aziza
- **Email:** CDCC006D6X2179@student.devacademy.id
- **ID Dicoding:** CDCC006D6X2179

## Menentukan Pertanyaan Bisnis

**SMART Question** adalah sebuah framework untuk merumuskan pertanyaan secara terstruktur agar memeperoleh informasi yang mendalam.

* **Spesific (Spesifik)**
  * Pertanyaan harus jelas, fokus pada sebuah topik tertentu, dan tidak bermakna ganda. Hindari pertanyaan yang terlalu luas.
    * Salah: Bagaimana cara meningkatkan penjualan?
    * Benar: Faktor apa saja yang memengaruhi penurunan penjualan produk kategori elektronik di wilayah Jakarta selama kuartal terakhir?
* **Measurable (Terukur)**
  * Pertanyaan harus bisa dijawab dengan angka atau matrix yang konkret, harus tahu apa yang akan dihitung.
    * Salah: Apakah pelanggan senang dengan layanan kita?
    * Benar: Berapa skor rata-rata Customer Satisfaction untuk layanan purna jual bulan ini dibandingkan bulan lalu?
* **Action-Oriented (Berorientasi Aksi)**
  * Hasil dari pertanyaan harus bisa memberikan arahan untuk melakukan tindakan nyata. Jika pertanyaan terjawab, stakeholder harus tahu apa langkah selanjutnya.
    * Salah: Mengapa orang suka berbelanja?
    * Benar: Fitur apa pada aplikasi yang paling sering digunakan sebelum pengguna memutuskan untuk melakukan checkout?
* **Relevant (Relevan)**
  * Hasil dari pertanyaan harus sejalan dengan tujuan utama bisnis atau masalah yang sedang dihadapi.
    * Salah: Menanyakan tentang stok gudang saat masalah utamanya adalah efektivitas kampanye media sosial.
    * Benar: Apakah kampanye iklan di Instagram memberikan Return on Ad Spend (ROAS) yang lebih tinggi dibandingkan iklan di TikTok?
* **Time-bound (Terikat Waktu)**
  * Pertanyaan harus ada batasan waktu yang jelas agar analisis memiliki konteks yang tepat.
    * Salah: Berapa banyak pengguna baru kita?
    * Benar: Berapa tingkat pertumbuhan pengguna baru secara bulanan (Month-over-Month) sepanjang tahun 2025?

**Contoh pertanyaan bisnis yang memenuhi seluruh elemen SMART**

***"Faktor apa saja yang memengaruhi penurunan conversion rate pada pengguna aplikasi Android di wilayah Jabodetabek sebesar 5% selama periode Flash Sale Maret 2026?"***

Keterangan:

- **Specific**: Fokus pada "penurunan conversion rate" untuk "aplikasi Android" di "Jabodetabek". Bukan sekadar penjualan turun.
- **Measurable**: Ada angka konkret yang ingin dianalisis, yaitu penurunan sebesar "5%".
- **Action-Oriented**: Dengan mengetahui faktor penyebabnya misalnya bug pada versi Android tertentu atau kendala logistik di Jabodetabek, tim bisa langsung melakukan perbaikan teknis atau operasional.
- **Relevant**: Penurunan konversi saat Flash Sale adalah masalah kritis bagi bisnis retail/e-commerce.
- **Time-bound**: Dibatasi pada periode spesifik "Flash Sale Maret 2026".

### Pertanyaan Bisnis untuk Dataset Air Quality

- **Pertanyaan 1:** Apakah rata-rata konsentrasi emisi gas buang kendaraan (NO2 dan CO) pada jam sibuk di stasiun pusat kota secara presentasi lebih tiggi dibandingkan dengan stasiun area pinggiran?
- **Pertanyaan 2:** Berapa presentasi waktu (dalam jam) dan total hari terjadinya kondisi saat konsentrasi NO2 melampaui 80 µg/m³ bersamaan dengan keceatan angin di bawah 1.5 m/s pada hari kerja selama musim dingin?

## Import Semua Packages/Library yang Digunakan
"""

# Impor library
!pip install gdown

import zipfile
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Impor data
# 1. Mengunduh ZIP file dari Google Drive
# File ID diambil melalui sumber dataset yang diberikan
file_id = '1RhU3gJlkteaAQfyn9XOVAz7a5o1-etgr'
output_zip_path = 'air_quality_data.zip'

print(f"Downloading air quality data (ID: {file_id})...")
gdown.download(f'https://drive.google.com/uc?id={file_id}', output_zip_path, quiet=False)
print("Download complete.")

# 2. Membuat direktori untuk mengekstrak dokumen
extract_dir = 'air_quality_data_extracted'
os.makedirs(extract_dir, exist_ok=True)

# 3. Membuka ZIP file
print(f"Extracting contents of {output_zip_path} to {extract_dir}...")
with zipfile.ZipFile(output_zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)
print("Extraction complete.")

# 4. Melihat daftar dataset dan mencari CSV secara rekursif
print("\nMencari file CSV...")
csv_files_paths = []
for root, _, files in os.walk(extract_dir):
    for file in files:
        if file.endswith('.csv'):
            csv_files_paths.append(os.path.join(root, file))

dataframes = {}
if csv_files_paths:
    print("File CSV ditemukan:")
    for path in csv_files_paths:
        print(f"- {path}")
        # Menggunakan nama file sebagai kunci di kamus dataframes
        file_name = os.path.basename(path).replace('.csv', '')
        try:
            dataframes[file_name] = pd.read_csv(path)
            print(f"  '{file_name}' berhasil dimuat. Bentuk: {dataframes[file_name].shape}")
        except Exception as e:
            print(f"  Gagal memuat '{file_name}': {e}")

    if dataframes:
        print("\nSemua data berhasil dimuat ke dalam kamus 'dataframes'.")
        # Untuk kemudahan, set 'df' ke DataFrame pertama yang dimuat (jika ada)
        # Ini akan memastikan sel penilaian sebelumnya masih bisa berfungsi untuk satu df
        # Namun, untuk penilaian seluruhnya, kita akan iterasi 'dataframes'.
        df = next(iter(dataframes.values()))
    else:
        print("Tidak ada DataFrame yang berhasil dimuat.")
        df = None
else:
    print("\nTidak ada file CSV yang ditemukan di direktori hasil ekstraksi.")
    df = None

"""## Data Wrangling

### Gathering Data

#### Load df
"""

# Membuat variabel baru untuk membaca data dari salah satu file CSV yang diekstrak

changping_file_path = '/content/air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Changping_20130301-20170228.csv'
changping_df = pd.read_csv(changping_file_path)

print(f"Data dari {changping_file_path} berhasil dimuat ke variabel 'changping_df'.")
print("Berikut 5 baris pertama dari 'changping_df':")
print(changping_df.head())

"""### Assessing Data

#### Identifying the problem
"""

print('--- Assessing Data for All CSV Files ---')

if 'dataframes' in locals() and dataframes:
    for name, df_item in dataframes.items():
        print(f"\n=== {name} ===")
        print('\n--- Informasi DataFrame ---')
        df_item.info()

        print('\n--- Missing Values per Kolom ---')
        print(df_item.isnull().sum())

        print('\n--- Jumlah Data Duplikat ---')
        print(f'Jumlah baris duplikat: {df_item.duplicated().sum()}')

        print('\n--- Statistik Deskriptif untuk Kolom Numerik ---')
        display(df_item.describe())

        print('\n--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---')
        display(df_item.describe(include='all'))
else:
    print("Tidak ada DataFrame yang ditemukan untuk dinilai. Pastikan sel loading data sudah dijalankan.")

"""### Cleaning Data"""

combined_df = pd.concat(dataframes.values(), ignore_index=True)

print("5 baris pertama dari combined_df:")
print(combined_df.head())
print(f"\nBentuk combined_df: {combined_df.shape}")

if 'year' in combined_df.columns and 'month' in combined_df.columns and 'day' in combined_df.columns and 'hour' in combined_df.columns:
    combined_df['datetime'] = pd.to_datetime(combined_df[['year', 'month', 'day', 'hour']])
    combined_df = combined_df.drop(columns=['year', 'month', 'day', 'hour'])
    print("  -> Kolom 'datetime' berhasil dibuat dan kolom waktu asli dihapus.")
else:
    print("  -> Kolom tahun, bulan, hari, atau jam tidak ditemukan. Kolom 'datetime' diasumsikan sudah ada.")

# Membuat kolom turunan untuk 'hari dalam seminggu' dan 'musim'
if 'datetime' in combined_df.columns:
    if 'day_of_week' not in combined_df.columns:
        combined_df['day_of_week'] = combined_df['datetime'].dt.day_name()
        print("  -> Kolom 'day_of_week' berhasil dibuat.")
    else:
        print("  -> Kolom 'day_of_week' sudah ada.")

    if 'is_weekday' not in combined_df.columns:
        combined_df['is_weekday'] = combined_df['datetime'].dt.dayofweek < 5
        print("  -> Kolom 'is_weekday' berhasil dibuat.")
    else:
        print("  -> Kolom 'is_weekday' sudah ada.")

    def get_season(month):
        if month in [12, 1, 2]:
            return 'Winter'
        elif month in [3, 4, 5]:
            return 'Spring'
        elif month in [6, 7, 8]:
            return 'Summer'
        else:
            return 'Autumn'

    if 'season' not in combined_df.columns:
        combined_df['season'] = combined_df['datetime'].dt.month.apply(get_season)
        print("  -> Kolom 'season' berhasil dibuat.")
    else:
        print("  -> Kolom 'season' sudah ada.")
else:
    print("  -> Kolom 'datetime' tidak ditemukan, melewatkan pembuatan kolom turunan waktu.")

# Mengidentifikasi dan mengklasifikasikan setiap stasiun sebagai 'pusat kota' atau 'pinggiran'
if 'station' in combined_df.columns and 'location_type' not in combined_df.columns:
    suburban_stations = ['Changping', 'Dingling', 'Huairou', 'Shunyi', 'Wanliu']
    city_center_stations = ['Aotizhongxin', 'Dongsi', 'Guanyuan', 'Gucheng', 'Nongzhanguan', 'Tiantan', 'Wanshouxigong']

    def classify_station_location(station_name):
        if station_name in suburban_stations:
            return 'Suburban'
        elif station_name in city_center_stations:
            return 'City Center'
        else:
            return 'Unknown'

    combined_df['location_type'] = combined_df['station'].apply(classify_station_location)
    print("  -> Kolom 'location_type' untuk stasiun berhasil dibuat.")
else:
    print("  -> Kolom 'location_type' sudah ada atau kolom 'station' tidak ditemukan.")

"""#### Fixing lost value"""

# Menangani nilai yang hilang (missing values)
print("\n--- Menangani Nilai yang Hilang ---")
print("Jumlah nilai yang hilang sebelum imputasi:")
initial_missing = combined_df.isnull().sum()[combined_df.isnull().sum() > 0]
if not initial_missing.empty:
    print(initial_missing)
else:
    print("Tidak ada nilai yang hilang sebelum imputasi.")

numerical_cols = combined_df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = combined_df.select_dtypes(include='object').columns.tolist()

# Hapus kolom 'No' dari daftar numerik untuk imputasi jika ada
if 'No' in numerical_cols:
    numerical_cols.remove('No')

print("\n  -> Melakukan imputasi kolom numerik dengan median...")
for col in numerical_cols:
    if combined_df[col].isnull().any():
        median_val = combined_df[col].median()
        combined_df[col].fillna(median_val, inplace=True)
        print(f"    Kolom '{col}' diimputasi dengan median: {median_val}")

print("\n  -> Melakukan imputasi kolom kategorikal dengan modus...")
for col in categorical_cols:
    if combined_df[col].isnull().any():
        # Untuk 'wd' yang memiliki missing values, kita isi dengan 'Unknown' agar tidak bias pada modus
        if col == 'wd':
            combined_df[col].fillna('Unknown', inplace=True)
            print(f"    Kolom '{col}' diimputasi dengan 'Unknown'.")
        else:
            mode_val = combined_df[col].mode()[0]
            combined_df[col].fillna(mode_val, inplace=True)
            print(f"    Kolom '{col}' diimputasi dengan modus: {mode_val}")

print("\nJumlah nilai yang hilang setelah imputasi:")
missing_after_imputation = combined_df.isnull().sum()[combined_df.isnull().sum() > 0]
if missing_after_imputation.empty:
    print("Tidak ada nilai yang hilang setelah imputasi.")
else:
    print(missing_after_imputation)

print("\n--- Ringkasan DataFrame setelah Preprocessing dan Cleaning ---")
combined_df.info()
print("\n5 baris pertama dari combined_df setelah semua preprocessing:")
print(combined_df.head())

"""## Exploratory Data Analysis (EDA)

### Explore

## Visualization & Explanatory Analysis

### Pertanyaan 1: Apakah rata-rata konsentrasi emisi gas buang kendaraan (NO2 dan CO) pada jam sibuk di stasiun pusat kota secara presentasi lebih tiggi dibandingkan dengan stasiun area pinggiran?
"""

# 1. Mendefinisikan 'jam sibuk' (07:00-09:00 dan 16:00-18:00).
rush_hour_morning = (combined_df['datetime'].dt.hour >= 7) & (combined_df['datetime'].dt.hour < 10)
rush_hour_evening = (combined_df['datetime'].dt.hour >= 16) & (combined_df['datetime'].dt.hour < 19)

# 2. Memfilter data hanya untuk jam sibuk.
rush_hour_df = combined_df[rush_hour_morning | rush_hour_evening].copy()
print(f"Data jam sibuk berhasil difilter. Jumlah data: {len(rush_hour_df)} baris.")

# 3. Mengelompokkan data berdasarkan jenis stasiun (pusat kota vs pinggiran).
# 4. Menghitung rata-rata konsentrasi NO2 dan CO untuk masing-masing kelompok.
average_emissions = rush_hour_df.groupby('location_type')[['NO2', 'CO']].mean()
print("\nRata-rata konsentrasi NO2 dan CO selama jam sibuk berdasarkan tipe lokasi:")
print(average_emissions)

# Memisahkan rata-rata untuk pusat kota dan pinggiran
if 'City Center' in average_emissions.index and 'Suburban' in average_emissions.index:
    city_center_avg = average_emissions.loc['City Center']
    suburban_avg = average_emissions.loc['Suburban']

    print("\n--- Perbandingan Rata-rata Emisi ---")
    print(f"Rata-rata NO2 di Pusat Kota: {city_center_avg['NO2']:.2f}")
    print(f"Rata-rata NO2 di Pinggiran: {suburban_avg['NO2']:.2f}")
    print(f"Rata-rata CO di Pusat Kota: {city_center_avg['CO']:.2f}")
    print(f"Rata-rata CO di Pinggiran: {suburban_avg['CO']:.2f}")

# 5. Menghitung perbandingan persentase antara rata-rata konsentrasi di stasiun pusat kota dan pinggiran.

if 'City Center' in average_emissions.index and 'Suburban' in average_emissions.index:
    # Asumsi: Menghitung persentase perbedaan relatif terhadap area pinggiran
    percentage_diff_no2 = ((city_center_avg['NO2'] - suburban_avg['NO2']) / suburban_avg['NO2']) * 100
    percentage_diff_co = ((city_center_avg['CO'] - suburban_avg['CO']) / suburban_avg['CO']) * 100

    print("\n--- Perbandingan Persentase (Pusat Kota vs Pinggiran) ---")
    print(f"Konsentrasi NO2 di Pusat Kota {'lebih tinggi' if percentage_diff_no2 > 0 else 'lebih rendah'} {abs(percentage_diff_no2):.2f}% dibandingkan Pinggiran.")
    print(f"Konsentrasi CO di Pusat Kota {'lebih tinggi' if percentage_diff_co > 0 else 'lebih rendah'} {abs(percentage_diff_co):.2f}% dibandingkan Pinggiran.")

    # Menentukan apakah secara presentase lebih tinggi
    if percentage_diff_no2 > 0 and percentage_diff_co > 0:
        print("\nKesimpulan Sementara: Rata-rata konsentrasi emisi NO2 dan CO di stasiun pusat kota secara presentasi lebih tinggi dibandingkan dengan stasiun area pinggiran.")
    elif percentage_diff_no2 < 0 and percentage_diff_co < 0:
        print("\nKesimpulan Sementara: Rata-rata konsentrasi emisi NO2 dan CO di stasiun pusat kota secara presentasi lebih rendah dibandingkan dengan stasiun area pinggiran.")
    else:
        print("\nKesimpulan Sementara: Perbandingan konsentrasi emisi NO2 dan CO di stasiun pusat kota dan pinggiran menunjukkan pola yang bervariasi.")
else:
    print("\nTidak dapat melakukan perbandingan persentase karena data untuk 'City Center' atau 'Suburban' tidak lengkap.")

"""**Insight:**

**Rata-rata Emisi:** Selama jam sibuk (07:00-09:00 dan 16:00-18:00), rata-rata konsentrasi NO2 dan CO lebih tinggi di stasiun Pusat Kota dibandingkan stasiun Pinggiran.
    *   Rata-rata NO2 di Pusat Kota: **52,40 µg/m³**
    *   Rata-rata NO2 di Pinggiran: **42,41 µg/m³**
    *   Rata-rata CO di Pusat Kota: **1237,72 µg/m³**
    *   Rata-rata CO di Pinggiran: **1078,60 µg/m³**
*   **Perbedaan Persentase:**
    *   Konsentrasi NO2 di Pusat Kota **23,56% lebih tinggi** dibandingkan area Pinggiran.
    *   Konsentrasi CO di Pusat Kota **14,75% lebih tinggi** dibandingkan area Pinggiran.

### Pertanyaan 2: Berapa presentasi waktu (dalam jam) dan total hari terjadinya kondisi saat konsentrasi NO2 melampaui 80 µg/m³ bersamaan dengan keceatan angin di bawah 1.5 m/s pada hari kerja selama musim dingin?
"""

# 1. Memfilter data untuk 'hari kerja' dan 'musim dingin'.
winter_weekday_df = combined_df[(combined_df['is_weekday'] == True) & (combined_df['season'] == 'Winter')].copy()
print(f"Data difilter untuk hari kerja di musim dingin. Jumlah data: {len(winter_weekday_df)} baris.")

# Menghitung total jam dan hari unik yang diamati selama hari kerja di musim dingin
total_winter_weekday_hours = len(winter_weekday_df)
total_winter_weekday_days = winter_weekday_df['datetime'].dt.date.nunique()
print(f"Total jam di hari kerja musim dingin: {total_winter_weekday_hours}")
print(f"Total hari unik di hari kerja musim dingin: {total_winter_weekday_days}")

# 2. Mengidentifikasi data di mana konsentrasi NO2 > 80 µg/m³ DAN kecepatan angin (WSPM) < 1.5 m/s.
# Pastikan kolom NO2 dan WSPM tidak null (meskipun sudah diimputasi, ini untuk keamanan)
condition_met_df = winter_weekday_df[
    (winter_weekday_df['NO2'] > 80) &
    (winter_weekday_df['WSPM'] < 1.5)
].copy()

print(f"Data memenuhi kondisi NO2 > 80 µg/m³ dan WSPM < 1.5 m/s: {len(condition_met_df)} baris.")

# 3. Menghitung total jam (jumlah baris) yang memenuhi kondisi ini.
total_hours_condition_met = len(condition_met_df)
print(f"Total jam yang memenuhi kondisi: {total_hours_condition_met}")

# 4. Menghitung total hari unik yang memenuhi kondisi ini.
total_days_condition_met = condition_met_df['datetime'].dt.date.nunique()
print(f"Total hari unik yang memenuhi kondisi: {total_days_condition_met}")

# 5. Menghitung persentase jam dan hari tersebut terhadap total jam dan hari yang diamati selama hari kerja di musim dingin.
percentage_hours = (total_hours_condition_met / total_winter_weekday_hours) * 100 if total_winter_weekday_hours > 0 else 0
percentage_days = (total_days_condition_met / total_winter_weekday_days) * 100 if total_winter_weekday_days > 0 else 0

print(f"\nPersentase waktu (dalam jam) kondisi terpenuhi: {percentage_hours:.2f}%")
print(f"Persentase total hari kondisi terpenuhi: {percentage_days:.2f}%")

"""**Insight:**

 **Data Terfilter:** Analisis berfokus pada **74,592 jam** di **259 hari unik** yang diklasifikasikan sebagai hari kerja musim dingin.
*   **Kejadian Kondisi Kritis:** Kondisi kritis spesifik di mana konsentrasi NO2 melebihi 80 µg/m³ dan kecepatan angin (WSPM) di bawah 1.5 m/s terjadi selama:
    *   **Total Jam:** 15,627 jam
    *   **Total Hari Unik:** 224 hari
*   **Persentase Kejadian:**
    *   Kondisi tersebut terjadi dalam **20.95%** dari total jam hari kerja musim dingin.
    *   Kondisi tersebut terjadi pada **86.49%** dari total hari kerja musim dingin.

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion & Recommendation

- **Conclusion pertanyaan 1:**
Berdasarkan analisis, rata-rata konsentrasi emisi gas buang kendaraan (NO2 dan CO) selama jam sibuk di stasiun pusat kota secara signifikan lebih tinggi dibandingkan di stasiun area pinggiran. Hal ini menunjukkan bahwa pusat kota mengalami polusi udara yang lebih besar dari polutan-polutan ini, terutama selama waktu lalu lintas padat, kemungkinan besar karena kepadatan lalu lintas yang lebih tinggi dan potensi sumber emisi lokal yang lebih banyak.

- **Conclusion pertanyaan 2:**
Selama hari kerja musim dingin, kondisi kritis konsentrasi NO2 tinggi (di atas 80 µg/m³) yang disertai dengan kecepatan angin rendah (di bawah 1.5 m/s) sering terjadi. Meskipun kondisi ini menyumbang sekitar **21% dari total jam**, namun berdampak pada **86.5% dari semua hari kerja musim dingin** yang substansial. Persentase hari yang tinggi ini menunjukkan bahwa kondisi lingkungan seperti itu merupakan karakteristik hari kerja musim dingin dan kemungkinan berkontribusi pada tantangan kualitas udara yang persisten, karena kecepatan angin yang rendah menghambat penyebaran polutan. Investigasi lebih lanjut mengenai waktu spesifik dalam sehari di mana kondisi ini paling sering terjadi dapat memberikan wawasan yang lebih terarah.

**Rekomendasi Action Item:**

Berdasarkan analisis kualitas udara di stasiun perkotaan dan pinggiran kota, serta kondisi NO2 tinggi saat kecepatan angin rendah di musim dingin, berikut adalah beberapa rekomendasi aksi:

1.  **Penguatan Kebijakan Transportasi dan Emisi:** Menerapkan kebijakan yang lebih ketat terkait standar emisi kendaraan, terutama di pusat kota, dan mempromosikan secara aktif penggunaan transportasi publik, sepeda, serta kendaraan listrik. Ini dapat membantu mengurangi konsentrasi NO2 dan CO pada jam sibuk.
2.  **Sistem Peringatan Dini Kualitas Udara yang Lebih Proaktif:** Mengembangkan dan mengimplementasikan sistem peringatan dini yang tidak hanya memberikan informasi real-time, tetapi juga prediksi kualitas udara, khususnya untuk kondisi 'NO2 tinggi dan angin rendah' selama musim dingin. Peringatan ini harus mencakup saran tindakan bagi warga (misalnya, mengurangi aktivitas luar ruangan, menggunakan masker).
3.  **Pengembangan Infrastruktur Hijau:** Berinvestasi dalam peningkatan ruang hijau dan vegetasi di area perkotaan yang padat. Tumbuhan dapat membantu menyaring polutan udara dan meningkatkan kualitas udara secara alami.
4.  **Penelitian Lanjutan tentang Sumber Emisi Lokal:** Melakukan studi lebih lanjut untuk mengidentifikasi sumber emisi spesifik (selain kendaraan) yang mungkin berkontribusi terhadap tingkat polusi tinggi di pusat kota, serta mencari solusi mitigasi yang ditargetkan.
"""

combined_df.to_csv('air_quality_combined.csv', index=False)
print('Data combined_df berhasil disimpan ke air_quality_combined.csv')
